# Generated by Django 5.0.8 on 2024-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_yapim_yili',
            field=models.DateField(blank=True, null=True),
        ),
    ]
