# Generated by Django 5.0.8 on 2024-08-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_film_yapim_yili'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
