# Generated by Django 5.0.8 on 2024-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='basrol_oyunculari',
            field=models.CharField(blank=True, default='Leonardo di Caprio', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
