# Generated by Django 5.0.8 on 2024-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_basrol_oyunculari'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='basrol_oyunculari',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
