# Generated by Django 5.0.8 on 2024-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_category_slug_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resim',
            field=models.ImageField(upload_to='movies'),
        ),
    ]
