# Generated by Django 5.0.8 on 2024-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='oyuncular',
            field=models.ManyToManyField(to='movies.cast'),
        ),
    ]
