# Generated by Django 5.0.8 on 2024-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='movies.category'),
        ),
    ]
