# Generated by Django 5.0.8 on 2024-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_movie_category_movie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='goruntulenme_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, to='movies.category'),
        ),
    ]
