# Generated by Django 5.0.8 on 2024-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_dislikes_movie_likes_usermovieinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovieinteraction',
            name='disliked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermovieinteraction',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
