# Generated by Django 5.0.8 on 2024-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_usermovieinteraction_disliked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovieinteraction',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermovieinteraction',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
