# Generated by Django 5.0.8 on 2024-09-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_alter_userprofile_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='yorum_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yorum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='yorum_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie'),
        ),
    ]
