# Generated by Django 5.0.8 on 2024-09-10 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_yorum_dislikes_yorum_likes_alter_yorum_film'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='sikayet_edenler',
            field=models.ManyToManyField(blank=True, related_name='sikayet_ettigi_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
