# Generated by Django 5.0.8 on 2024-09-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_remove_yorum_sikayet_sayisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SikayetNedeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YorumSikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikayet_tarihi', models.DateTimeField(auto_now_add=True)),
                ('neden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.sikayetnedeni')),
                ('sikayet_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sikayetler', to='movies.yorum')),
            ],
        ),
    ]
