# Generated by Django 5.0.8 on 2024-09-14 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_sikayetnedeni_yorumsikayet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(default='Uyarı Mesajı', max_length=255)),
                ('mesaj', models.TextField()),
                ('okundu_mu', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
