# Generated by Django 5.0.8 on 2024-09-14 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_mesaj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='okundu_mu',
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='alici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alici_mesajlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='gonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gonderen_mesajlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
