# Generated by Django 5.0.8 on 2024-09-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_remove_mesaj_okundu_mu_alter_mesaj_alici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dondurulma_bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hesap_donduruldu',
            field=models.BooleanField(default=False),
        ),
    ]
