# Generated by Django 5.0.8 on 2024-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_userprofile_hesap_donduruldu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hesap_donduruldu',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hesap_dondurulma_bitis_zamani',
        ),
    ]
