# Generated by Django 5.0.8 on 2024-09-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0050_userprofile_hesap_donduruldu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movies.yorum'),
        ),
    ]
