# Generated by Django 5.0.8 on 2024-09-24 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0051_yorum_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=255)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alici_mesajlari2', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderen_mesajlari2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
