# Generated by Django 5.0.8 on 2024-10-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0054_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciTakibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('takip_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_ediyor', to=settings.AUTH_USER_MODEL)),
                ('takip_edilen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_ediliyor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('takip_eden', 'takip_edilen')},
            },
        ),
    ]
