# Generated by Django 5.0.8 on 2024-10-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0056_kullaniciengelleme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KullaniciEngelleme',
        ),
    ]
