# Generated by Django 5.0.8 on 2024-10-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0057_delete_kullaniciengelleme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciEngelleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engellenen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engelleniyor', to=settings.AUTH_USER_MODEL)),
                ('engelleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engelliyor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('engelleyen', 'engellenen')},
            },
        ),
    ]
