# Generated by Django 5.0.8 on 2024-10-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0058_kullaniciengelleme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Oyuncular'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='favoritemovie',
            options={'verbose_name_plural': 'Favori Filmler'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name_plural': 'Arkadaşlık İstekleri'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name_plural': 'Arkadaşlıklar'},
        ),
        migrations.AlterModelOptions(
            name='kullaniciengelleme',
            options={'verbose_name_plural': 'Kullanıcı Engellemeleri'},
        ),
        migrations.AlterModelOptions(
            name='kullanicitakibi',
            options={'verbose_name_plural': 'Kullanıcı Takipleri'},
        ),
        migrations.AlterModelOptions(
            name='mesaj',
            options={'verbose_name_plural': 'Uyarı Mesajları'},
        ),
        migrations.AlterModelOptions(
            name='mesaj2',
            options={'verbose_name_plural': 'Genel Mesajlaşmalar'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Derecelendirmeler'},
        ),
        migrations.AlterModelOptions(
            name='sikayetnedeni',
            options={'verbose_name_plural': 'Şikayet Nedenleri'},
        ),
        migrations.AlterModelOptions(
            name='usermovieinteraction',
            options={'verbose_name_plural': 'Kullanıcı ve Film Etkileşimleri'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'verbose_name_plural': 'İzlenilen Filmler'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name_plural': 'İzlenecek Filmler'},
        ),
        migrations.AlterModelOptions(
            name='yorum',
            options={'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='yorumsikayet',
            options={'verbose_name_plural': 'Yorum Şikayetleri'},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_accepted',
        ),
    ]
