# Generated by Django 5.0.8 on 2024-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0059_alter_cast_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dil',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('yabancı', 'Yabancı')], default='yabancı', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='filmler', to='movies.category'),
        ),
    ]
