# Generated by Django 5.0.8 on 2024-10-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0060_movie_dil_alter_movie_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='dil',
        ),
    ]
